import {assertContinuationSettled} from '../electron/continuation-pack.mjs';
import os from 'node:os';
import {assertSessionNotMoving,resolveMovedSessionCwd} from "../electron/session-move.mjs";
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {applyAgentAccess,applyWindowAgentAccess} from '../electron/agent-access.mjs';
function peer(){return {sandbox:true,outside:false,setSandboxTerminal(v){this.sandbox=v},setAllowOutsideProject(v){this.outside=v}}}
test('access changes reach live and parked clients in every window',()=>{const a=peer(),b=peer(),c=peer();const windows=new Map([[1,{agent:a,parkedAgents:new Map([['b',b]])}],[2,{agent:c,parkedAgents:new Map([['same',a]])}]]);assert.equal(applyWindowAgentAccess(windows,{sandboxTerminal:false,allowOutsideProject:true}),3);for(const p of [a,b,c]){assert.equal(p.sandbox,false);assert.equal(p.outside,true)}applyWindowAgentAccess(windows,{sandboxTerminal:true,allowOutsideProject:false});for(const p of [a,b,c]){assert.equal(p.sandbox,true);assert.equal(p.outside,false)}});
test('IPC sandbox and outside-project handlers apply their persisted value to parked clients',async()=>{const source=readFileSync(new URL('../electron/main.mjs',import.meta.url),'utf8');const a=peer(),b=peer();let state={sandboxTerminal:true,allowOutsideProject:false};const windows=new Map([[1,{agent:a,parkedAgents:new Map([['b',b]])}]]);for(const [channel,value] of [['agent:set-sandbox-terminal',false],['agent:set-allow-outside-project',true]]){const start=source.indexOf(`ipcMain.handle("${channel}", `);assert.ok(start>=0);const from=source.indexOf('async (_e, value) => {',start),end=source.indexOf('\n  });',from);const handler=vm.runInNewContext('('+source.slice(from,end+4)+')',{loadState:()=>({...state}),saveState:s=>{state=s},windowSessions:windows,applyWindowAgentAccess,maybeWarmDockerSandbox(){throw Error('disabling must not warm Docker')}});assert.equal(await handler(null,value),value)}for(const p of [a,b]){assert.equal(p.sandbox,false);assert.equal(p.outside,true)}});
test('ensureAgent refreshes owner settings when restoring parked or existing clients',async()=>{const source=readFileSync(new URL('../electron/window-session.mjs',import.meta.url),'utf8');const from=source.indexOf('export function ensureAgent('),end=source.indexOf('\nexport function disposeWindowSession(',from);const p={...peer(),ready:true,proc:{},cwd:'/fixture',sessionId:'old',setAllowWritesThisSession(){}};const ws={agent:null,parkedAgents:new Map([['old',p]]),generation:1,agentChain:Promise.resolve()};const fn=vm.runInNewContext('('+source.slice(from,end).replace(/^export /,'')+'\n)',{assertContinuationSettled,app:{getPath:()=>os.tmpdir()},assertSessionNotMoving,resolveMovedSessionCwd,applyAgentAccess,isSessionLive:()=>true,loadDesktopState:()=>({sandboxTerminal:false,allowOutsideProject:true}),takeParkedAgent(w,id){const p=w.parkedAgents.get(id);w.parkedAgents.delete(id);return p},parkLiveAgent(){throw Error('unexpected client switch')},rememberProjectOnWindow(){},restartBackgroundTaskTail(){},restoreParkedAgent(){return null}});assert.equal(await fn(ws,'/fixture',{resumeSessionId:'old'}),p);assert.equal(p.sandbox,false);assert.equal(p.outside,true);p.sandbox=true;p.outside=false;await fn(ws,'/fixture',{resumeSessionId:'old'});assert.equal(p.sandbox,false);assert.equal(p.outside,true)});
