import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {ensureStore,ensureObject,writeRecord,readCurrent,listObjects,appendInbox,markInbox,writeConfig,bindSession,listInbox} from '../shared/working-knowledge/store.mjs';
import {uiCorrect,uiWithdraw} from '../shared/working-knowledge/updates.mjs';
import {exportWorkingObject,stageWorkingBundle,previewWorkingBundle,acceptWorkingBundle,listPendingWorkingBundles,validateWorkingBundle} from '../shared/working-knowledge/sync.mjs';
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wk-transfer-'));t.after(()=>{delete process.env.GROK_DESKTOP_WK_ROOT;fs.rmSync(root,{recursive:true,force:true});});const a=path.join(root,'a'),b=path.join(root,'b');ensureStore(a);ensureStore(b);ensureObject(a,'sample',{title:'合成示例'});writeRecord(a,{id:'baseline',objectId:'sample',kind:'decision',text:'同意两周试用',epistemic:'user_said',source:{type:'user',sessionId:'A',quote:'同意两周试用'}});return {a,b,root};}
function accept(root,bundle){const p=stageWorkingBundle(root,bundle);return acceptWorkingBundle(root,{token:p.token,localHead:p.localHead,choice:'continue'});}
test('portable object bundle is explicit, hash-checked and excludes config, credentials, bindings and unknown files',t=>{const {a,b}=setup(t);for(const name of ['auth.json','mcp_credentials.json','config.toml'])fs.writeFileSync(path.join(a,'objects/sample',name),'credential-fixture-not-exported');writeConfig(a,{probeArmed:true,currentObjectId:'sample'});const bundle=exportWorkingObject(a,'sample',{machine:'primary'});assert.doesNotMatch(JSON.stringify(bundle),/credential-fixture|probeArmed|config.toml/);accept(b,bundle);assert.equal(readCurrent(b,'sample').items[0].source.sessionId,'A');assert.equal(listObjects(b)[0].title,'合成示例');assert.deepEqual(exportWorkingObject(b,'sample').data,bundle.data);assert.equal(exportWorkingObject(b,'sample').head,bundle.head);});
test('two physical stores diverge: concurrency cannot be settled by timestamps and both originals remain',t=>{const {a,b}=setup(t);accept(b,exportWorkingObject(a,'sample'));uiCorrect(a,{objectId:'sample',id:'baseline',text:'本机改为一周',sessionId:'A'});uiCorrect(b,{objectId:'sample',id:'baseline',text:'僚机改为三周',sessionId:'B'});fs.utimesSync(path.join(a,'objects/sample/current.json'),new Date(0),new Date(0));const original=fs.readFileSync(path.join(a,'objects/sample/records.jsonl'),'utf8');const p=stageWorkingBundle(a,exportWorkingObject(b,'sample'));assert.equal(p.kind,'conflict');assert.throws(()=>acceptWorkingBundle(a,{...p,choice:'continue'}),/独立更新/);const result=acceptWorkingBundle(a,{...p,choice:'keep-local'});assert.equal(fs.readFileSync(path.join(result.backup,'records.jsonl'),'utf8'),original);assert.ok(readCurrent(a,'sample').items.some(r=>r.text==='本机改为一周'));const back=stageWorkingBundle(b,exportWorkingObject(a,'sample'));assert.equal(back.kind,'incoming-ahead');acceptWorkingBundle(b,{...back,choice:'continue'});assert.deepEqual(readCurrent(a,'sample'),readCurrent(b,'sample'));});
test('incoming conflict choice retains local backup; tombstone cannot revive from an older bundle',t=>{const {a,b}=setup(t);const old=exportWorkingObject(a,'sample');accept(b,old);uiCorrect(a,{objectId:'sample',id:'baseline',text:'本机新想法'});uiWithdraw(b,{objectId:'sample',id:'baseline'});const p=stageWorkingBundle(a,exportWorkingObject(b,'sample'));assert.equal(p.kind,'conflict');const r=acceptWorkingBundle(a,{...p,choice:'use-incoming'});assert.ok(fs.existsSync(r.backup));assert.ok(!readCurrent(a,'sample').items.some(r=>r.id==='baseline'));const earlier=stageWorkingBundle(a,old);assert.equal(earlier.kind,'local-ahead');assert.throws(()=>acceptWorkingBundle(a,{...earlier,choice:'use-incoming'}),/不能回退/);});
test('a correction after preview invalidates acceptance, including identical integer versions on independent machines',t=>{const {a,b}=setup(t);accept(b,exportWorkingObject(a,'sample'));uiCorrect(b,{objectId:'sample',id:'baseline',text:'来自僚机'});const p=stageWorkingBundle(a,exportWorkingObject(b,'sample'));writeRecord(a,{objectId:'sample',kind:'unknown',text:'本机刚补的问题'});assert.throws(()=>acceptWorkingBundle(a,{...p,choice:'continue'}),/预览后/);assert.ok(listPendingWorkingBundles(a).some(r=>r.token===p.token));});
test('interruption between original backup and installation is recovered by ordinary object listing in a fresh module consumer',t=>{const {a,b}=setup(t);accept(b,exportWorkingObject(a,'sample'));uiCorrect(b,{objectId:'sample',id:'baseline',text:'后继版本'});fs.writeFileSync(path.join(a,'objects/sample/user-original.txt'),'keep locally');const p=stageWorkingBundle(a,exportWorkingObject(b,'sample'));assert.throws(()=>acceptWorkingBundle(a,{...p,choice:'continue'},{afterBackup(){throw Error('simulated power loss');}}),/power loss/);assert.ok(!fs.existsSync(path.join(a,'objects/sample')));assert.equal(listObjects(a)[0].id,'sample');assert.equal(fs.readFileSync(path.join(a,'objects/sample/user-original.txt'),'utf8'),'keep locally');assert.ok(readCurrent(a,'sample').items.some(r=>r.text==='后继版本'));assert.equal(previewWorkingBundle(a,p.token).kind,'equal');});
test('tampered payload, corrupted history, symlink files, and arbitrary file names are not silently accepted',t=>{const {a,b,root}=setup(t);const bundle=exportWorkingObject(a,'sample');bundle.data.current.items[0].text='tampered';assert.throws(()=>stageWorkingBundle(b,bundle),/校验/);fs.writeFileSync(path.join(a,'objects/sample/records.jsonl'),'{bad');assert.throws(()=>exportWorkingObject(a,'sample'));fs.unlinkSync(path.join(a,'objects/sample/records.jsonl'));fs.writeFileSync(path.join(root,'private.txt'),'[]');fs.symlinkSync(path.join(root,'private.txt'),path.join(a,'objects/sample/records.jsonl'));assert.throws(()=>exportWorkingObject(a,'sample'),/链接/);assert.equal(listObjects(b).length,0);});
test('inbox original identity and pending state move with the object, not host credentials',t=>{const {a,b}=setup(t);const one=appendInbox(a,{objectId:'sample',sessionId:'S1',cwd:'/one',text:'相同原话',source:'user'}),two=appendInbox(a,{objectId:'sample',sessionId:'S2',cwd:'/two',text:'相同原话',source:'user'});markInbox(a,'sample',one.id,{status:'processed'});const bundle=exportWorkingObject(a,'sample');const p=stageWorkingBundle(b,bundle);assert.equal(p.incomingPending,1);acceptWorkingBundle(b,{...p,choice:'continue'});assert.equal(listInbox(b,'sample','pending')[0].id,two.id);assert.equal(listInbox(b,'sample','pending')[0].sessionId,'S2');});
test('a real outgoing turn prepared before import cannot commit after another device changes the object',async t=>{const {a,b}=setup(t);writeConfig(a,{currentObjectId:'sample'});bindSession(a,{sessionId:'session-test',objectId:'sample',source:'user'});process.env.GROK_DESKTOP_WK_ROOT=a;const {wrapOutgoingPrompt,consumeTurnOutput}=await import('../electron/working-knowledge.mjs');const turn=wrapOutgoingPrompt({sessionId:'session-test',text:'旧回合',cwd:'/synthetic'});accept(b,exportWorkingObject(a,'sample'));uiCorrect(b,{objectId:'sample',id:'baseline',text:'更新的认识'});accept(a,exportWorkingObject(b,'sample'));const result=consumeTurnOutput({...turn,assistantText:'无论输出什么',sessionId:'session-test',objectId:'sample'});assert.equal(result.reason,'object-transferred');});
